# Base settings for the Netlify site
[build]
  publish = "dist"
  command = "npm run build"

# Headers to solve MIME type issues
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"
    
[[headers]]
  for = "/assets/*.ts"
  [headers.values]
    Content-Type = "text/javascript"
    
[[headers]]
  for = "/assets/*.tsx"
  [headers.values]
    Content-Type = "text/javascript"

# API redirect (must come before the SPA redirect)
[[redirects]]
  from = "/api/*"
  to = "https://subtle-caring-walleye.ngrok-free.app/:splat"
  status = 200
  force = true

# This makes sure all routes go to index.html for a SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200